name: Build VoltageOS ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib \
            g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev \
            ccache libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python-is-python3 \
            openjdk-11-jdk jq rsync

      - name: Initialize VoltageOS repo
        run: |
          mkdir voltage && cd voltage
          repo init -u https://github.com/VoltageOS/manifest.git -b fifteen
          repo sync -j$(nproc) --force-sync --no-tags --no-clone-bundle

      - name: Clone device, vendor, kernel trees
        run: |
          cd voltage
          # Replace below URLs with your actual repos
          git clone https://github.com/YourGitHub/device_oneplus_andes device/oneplus/andes
          git clone https://github.com/YourGitHub/vendor_oneplus_andes vendor/oneplus/andes
          git clone https://github.com/YourGitHub/kernel_oneplus_andes kernel/oneplus/andes

      - name: Setup build environment
        run: |
          cd voltage
          source build/envsetup.sh
          lunch voltage_andes-userdebug

      - name: Build VoltageOS ROM
        run: |
          cd voltage
          export USE_CCACHE=1
          ccache -M 10G
          make bacon -j$(nproc)

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoltageOS-ROM
          path: voltage/out/target/product/andes/*.zip
